### ISSUE TITLE
Repo size is very huge

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/api.haxe.org#3]
The repo is increasing with few mb per change on xml / theme change.

I suggest to reset history of the `gh-branch` on each deploy, unless there is a reason we want to keep the history.

**Comment by Simn** [comment]
I noticed this as well. This already has 600 MB of objects when cloning and it's only going to get worse.

**Comment by andyli** [comment]
It seems to be good now. A fresh clone of the repo will have a `.git` folder of ~70MB.
