### ISSUE TITLE
Use stable Haxe version

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/api.haxe.org#4]
Can we use a stable Haxe version for generating the api docs?

Because api.haxe.org was broken yesterday because of unicode related issues in Haxe development branch.

**Comment by andyli** [comment]
IIRC, we're using Haxe development because the libs (I think it's hxparse) need it.

**Comment by andyli** [comment]
Oh, not really, 3.4.7 is fine. The reason of using development was to take advantage of the speed of eval. Let's switch to 3.4.7.

**Comment by andyli** [comment]
It now fail with 

> The job exceeded the maximum time limit for jobs, and has been terminated.

:cry:

**Comment by andyli** [comment]
Switched to compiling Dox to cpp and it's even faster than eval!
