### ISSUE TITLE
sys.io.Process shouldn't link to lua process

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/api.haxe.org#5]
on https://api.haxe.org/Sys.html#command

Read the `sys.io.Process` api for a more complete way to start background processes.

`sys.io.Process` is linked to: <https://api.haxe.org/lua/lib/luv/Process.html#Process>

should probably be: <https://api.haxe.org/sys/io/Process.html>

**Comment by jcward** [comment]
Stumbled across this today... I'm assuming since the link isn't defined in the comment, it's a problem in dox?

**Comment by Gama11** [comment]
Same issue as https://github.com/HaxeFoundation/dox/issues/264.
