### ISSUE TITLE
version of dox used? (no deprecation notice at api doc site)

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/api.haxe.org#6]
Was just looking at <https://api.haxe.org/v/development/haxe/Utf8.html> and noticed there was no deprecation notice for that class (<https://github.com/HaxeFoundation/haxe/blob/b9df128719f0df33c86bf362c19b8a6599c7cfed/std/haxe/Utf8.hx#L29>).

Went to look at dox and saw that it should include those notices since 2018 or so: <https://github.com/HaxeFoundation/dox/commit/6c36cceaf26052d9b115126955050d0319f8e93c>. (Unless I'm misunderstanding that commit.)

**Comment by Aurel300** [comment]
I think dox might just be generating the deprecation notice visually on fields, not entire types.

**Comment by Gama11** [comment]
Closing in favor of #261.
